epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - http: 0.0.0.0:40772
    - unix: /var/run/mirakurun/mirakurun.sock

channels:
  - name: 'ＴＯＫＹＯ　ＭＸ１'
    type: 'GR'
    channel: '16'

  - name: 'フジテレビ'
    type: 'GR'
    channel: '21'

  - name: 'ＴＢＳ１'
    type: 'GR'
    channel: '22'

  - name: 'テレビ東京１'
    type: 'GR'
    channel: '23'

  - name: 'テレビ朝日'
    type: 'GR'
    channel: '24'

  - name: '日テレ１'
    type: 'GR'
    channel: '25'

  - name: 'ＮＨＫＥテレ１東京'
    type: 'GR'
    channel: '26'

  - name: 'ＮＨＫ総合１・東京'
    type: 'GR'
    channel: '27'

tuners:
  - name: PX4-T1
    types: [GR]
    command: >-
      recpt1 --device /dev/pxmlt5video0 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T2
    types: [GR]
    command: >-
      recpt1 --device /dev/pxmlt5video1 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T3
    types: [GR]
    command: >-
      recpt1 --device /dev/pxmlt5video2 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T4
    types: [GR]
    command: >-
      recpt1 --device /dev/pxmlt5video3 {{channel}} {{duration}} -
    disabled: false

  - name: PX4-T5
    types: [GR]
    command: >-
      recpt1 --device /dev/pxmlt5video4 {{channel}} {{duration}} -
    disabled: false

filters:
  decode-filter:
    command: arib-b25-stream-test
